### ISSUE TITLE
Bug - [default: PokestopLoop] - Error fetching route from provider: Operation timed out

### ISSUE THREAD

**Issue by DiogoRNeves** [jabbink/PokemonGoBot#1062]
**Description:**
When the follow_streets option is set to true, I started getting the error. Been betting at this location with follow_streets on for over one week. First occurrence (with timestamp in GMT) was:

14 Aug 02:51:55 [default: PokestopLoop] - Error fetching route from provider: Operation timed out

After that the bot does not move. Never happened before. Turning follow_streets off is the workaround I found.

**Steps to reproduce:**

1. Start the bot with follow_streets=true
2. When it times out, the error should appear

**Expected behavior:**
Walk around following streets

**Actual behavior:**
Bot stands there and loots pokéstops in range every 5 minutes and catches pokémon that show up there.

**Stacktrace (If it's a crash):**
14 Aug 02:51:55 [default: PokestopLoop] - Error fetching route from provider: Operation timed out

**Version:**
0.5.2

**Operating System:**
Mac OS X

**Java version:**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by Sieberkev** [comment]
This is already fixed in the development branch (#961) but not yet in the release JAR.

**Comment by DiogoRNeves** [comment]
Cool I'll build it and test. Will let you know if happens again.

Thanks.

**Comment by DiogoRNeves** [comment]
So... Still happening on db5d8e20ab422c8cc0dca2ded967691551b22a6c

14 Aug 13:33:46 [default: PokestopLoop] - Error fetching route from provider: Operation timed out

**Comment by Sieberkev** [comment]
Yep, found the culprit :) PR = made

**Comment by DiogoRNeves** [comment]
An it got merged. Gonna build and run it.

**Comment by DiogoRNeves** [comment]
Sorry... Still buggy... Fails to get route from provider and the just stays there...

**Comment by Sieberkev** [comment]
I'm running the current dev now, encountered a lot of errors, but he just walks from stop to stop now.

```
git pull
./gradlew clean
./gradlew build
./gradlew run
```

**Comment by DiogoRNeves** [comment]
You're right. Forgot git pull -.-

Sorry.

**Comment by AlexBoulyga** [comment]
Interestingly it seems to work now AS the bot is moving, but! It still shows the error message

**Comment by Sieberkev** [comment]
Well, running in a straight line thru buildings/rivers/... when you set follow_street=true technically remains an error ^_^

**Comment by AlexBoulyga** [comment]
But i get a connection timed out error. I will look at that more closely when testing my code next time

**Comment by Sieberkev** [comment]
Yeah, the external RouteProvider server is really unstable today...

**Comment by AlexBoulyga** [comment]
Hmm we use an external Route provider? So i guess you added the logic "if connection timed out, go straight line instead"? Nice!

**Comment by DiogoRNeves** [comment]
That's what he did :-)
