### ISSUE TITLE
API to follow streets doesn't retrieve data 

### ISSUE THREAD

**Issue by hlopes88** [jabbink/PokemonGoBot#1243]
**Description:**
When follow_streets=true, all the API calls to yournavigations.org doesn't retrieve data 
Example: 
http://yournavigation.org/api/dev/route.php?flat=40.863912614436515&flon=-8.623450691997188&tlat=40.864315&tlon=-8.622188&v=foot&fast=1
Answer: Server not ready to process requests. Please try again later.

**Steps to reproduce:**

1. Set follow_streets=true
2. Start bot

**Expected behavior:**
Bot should follow streets.

**Actual behavior:**
At this moment he is walking directly to the destination location.

**Stacktrace (If it's a crash):**
27 ago 20:30:16 [default: PokestopLoop] - Error fetching route from provider: Server returned HTTP response code: 503 for URL: http://yournavigation.org/api/dev/route.php?flat=40.8592722036296&flon=-8.62267964708135&tlat=40.858985&tlon=-8.624176&v=foot&fast=1

**Version:**
PokemonGoBot-0.6.0

**Operating System:**
Windows 10

**Java version:**
java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by jabbink** [comment]
Hi @hlopes88,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-29 21:30) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Sieberkev** [comment]
This is a known issue in the 0.6.0 release but is fixed in the current development branch :)

**Comment by Resistant-X** [comment]
For me the bot wanted to follow no roads. I always gotten an error message from yournavigation.org. I have looked at the source code and made a small change.

In FIle
src\main\kotlin\ink\abb\pogo\scraper\util\directions\RouteRequest.kt
In line 42 change
return "$routeProvider?flat=$olat&flon=$olng&tlat=$dlat&tlon=$dlng&v=foot&fast=1"
to
return "$routeProvider?flat=$olat&flon=$olng&tlat=$dlat&tlon=$dlng&v=bicycle&fast=1"

Now I have no more error messages from yournavigation.org and my bot follows again the streets.

P.s. Sorry for my bad english
(https://cloud.githubusercontent.com/assets/1244755/18050138/f8a30756-6dec-11e6-9d3d-9fc60fa1838d.PNG)

**Comment by MrBull** [comment]
@Resistant-X: I did as you suggested but I still have the error. I changed the "foot" to the "bicycle"; bot still shows the error. Does it have any other steps that I need to do to fix this?

**Comment by chongivan** [comment]
Hey @Resistant-X, could i have a copy of your ./bot-settings/default.json please?

**Comment by Sieberkev** [comment]
@MrBull do you have the release 0.6.0 JAR or the most recent development branch (where it is fixed)?

**Comment by MrBull** [comment]
@Sieberkev : I am using v0.6.0 Jar... Does it need to be the dev version for this to work? It would be helpful if you could give some guides here on how to get the files and implement them.

**Comment by Sieberkev** [comment]
Yes it is fixed in the dev version ([from source](https://github.com/jabbink/PokemonGoBot/blob/develop/USAGE.md#from-source)).

**Comment by jabbink** [comment]
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.
