### ISSUE TITLE
0.4.1 Release gets mad at 1.8 java

### ISSUE THREAD

**Issue by omar972** [jabbink/PokemonGoBot#256]
So I have 1.8 java on my system, and when I try to run the bot, I get this.

D:\POGO bot>java -jar pogo.scraper-all-0.4.1.jar
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'

has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

So, I literally just go into the registry, change Software\JavaSoft\Java Runtime Environment'\CurrentVersion from 1.8 to 1.7 and it works, but I prefer not to fake my version so can you please fix this? Seems like it shouldn't be a hard fix.

Also, is there a way to make the bot use pokeballs only? Right now it keeps using ultra balls then great balls even though I have in config: desired_catch_probability=0.6

**Comment by Dragunovam** [comment]
preferred_ball=ITEM_POKE_BALL has been absent in the latest **config.properties** file, so you should simply add it. Also, the latest release makes this new file **config-properties-conversion.json** to store the bot settings, if you happen to edit config.properties the new changes won't take effect until you remove **config-properties-conversion.json** in the bot-settings folder, or edit the **config-properties-conversion.json** file itself.

**Comment by jabbink** [comment]
Should be fixed in 0.4.2

**Comment by omar972** [comment]
Still not fixed.

D:\POGO bot>java -jar pogo.scraper-all-0.4.2.jar
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'

has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.
