### ISSUE TITLE
0.4.2 google login issue

### ISSUE THREAD

**Issue by karikkato** [jabbink/PokemonGoBot#319]
Logging in to game server...
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException
        at com.pokegoapi.auth.GoogleLogin.login(GoogleLogin.java:160)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:85)

I thought #317 would be my issue, but it's not... I can log in with PTC accounts just fine, only happens with my google account.

Further info java is at 1.8.0_92 and I'm on a mac, I'll see if I can reproduce (and try to debug) once I get home and can use my windows dev machine

**Comment by jabbink** [comment]
Version? The error is in Main.kt line 85. That file only has 82 lines.

**Comment by wartickler** [comment]
No login issue hear as of about 10 minutes ago on 0.4.2

**Comment by ceboks** [comment]
hello, im using it now, it says, get user to go to https://www.google.com/device and enter code, and then stuck, can you help me?

**Comment by 0rf3o** [comment]
i have similar problem with PTC account

Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Error in API Url
at com.pokegoapi.main.RequestHandler.sendServerRrequests(RequestHandler. java:149)
at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
at com.pokegoapi.api.PokemonGo. <init>(PokemonGo.java:66)
at ink.abb.pogo.scraper.Mainkt.main(Main.kt:107)

**Comment by karikkato** [comment]
interesting, this is using both the jar for 0.4.2 release and then got it again from the latest master and develop branches

I'm at the office now using my work mac so right so it might just be my machine, but like I said, PTC accounts work fine.

**Comment by ErusPenates** [comment]
PTC server  down ) xD

**Comment by jabbink** [comment]
@0rf3o remove the token from your config

And yes, Ptc is flaky, atm.

**Comment by SwipeX** [comment]
@jabbink this is actually an error on the API on the Development branch for google token refresh

**Comment by jabbink** [comment]
Well, "for google token refresh". Main cause of this happening is actually when using Ptc login.

Someone added that shitty branch in there again. Used to work.

**Comment by ErusPenates** [comment]
Can i create token for all time in google  ?

**Comment by jabbink** [comment]
Compile from source and it's hopefully fixed. I wouldn't suggest using this on a google account anyways.

**Comment by karikkato** [comment]
I like living life on the razors edge :)
but alas, no luck

Logging in to game server...
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException
        at com.pokegoapi.auth.GoogleLogin.login(GoogleLogin.java:160)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:49)

**Comment by WillymarJ** [comment]
my PTC account can not login, why ?

**Comment by okynk** [comment]
@WillymarJ PTC login server is down right now.. 
https://go.jooas.com/

**Comment by jabbink** [comment]
Back on topic @karikkato does removing the token from your config file fix the issue?

**Comment by ColeB27** [comment]
@jabbink it does, but right when the token line is filled. It fails to launch.

**Comment by karikkato** [comment]
I never had a token to begin with, also forgot to mention but after getting home I tried everything again on my windows 10 dev box and it gave me the same set of errors
I'm glad I have a copy of 0.4.1 because that still works like a charm!

**Comment by karikkato** [comment]
Update, just tried the 0.3.0 jar and it also fails with an error related to googlelogin, so I think this might just be an isolated issue with macs (or just my work mac) can someone using mac verifies this works for them?

**Comment by jabbink** [comment]
>my **work** mac

Using any corporate firewalls that mess with https (eg. man in the middle everything with a self signed cert that is installed on your work computer)?

**Comment by karikkato** [comment]
I had considered that it might be that, but when I tried using my phones wifi it still failed.
I would still like to hear the status from a personal mac user

**Comment by jabbink** [comment]
Should be fixed with 0.4.3

**Comment by karikkato** [comment]
@jabbink , 0.4.3 still doesn't work on my mac using google accounts, gives me a prompt to check credentials, but those are solid... At this point no other mac user has complained so it's probably just work related software messing with it, thanks for trying tho, cheers!
