### ISSUE TITLE
[QUESTION]GUI Branch

### ISSUE THREAD

**Issue by Pepejson** [jabbink/PokemonGoBot#493]
Hey, 

Could you explain me how to get GUI working? I've compiled the shilch-master branch and when I launched  the bot I got log in console saying that webserver is running but when I type in browser localhost:8000 nothing shows up.

Please close the issue as soon as you answer.

**Comment by marcx093** [comment]
I got the same issue :+1:

**Comment by shilch** [comment]
Are there any errors in the log?

**Comment by Pepejson** [comment]
Yeah, line 136-138. It doesn't show on other branches, just on yours with gui.

http://pastebin.com/ZRsZwcWn

**Comment by shilch** [comment]
weird, wait for the merge, maybe it is fixed then

**Comment by jabbink** [comment]
Possibly fixed on `develop`. If not: which browser are you using?

**Comment by Pepejson** [comment]
Issue still happening

Using Google Chrome on Win10. Running bot on Debian 8 with java -version output as following:
```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

**Comment by Dr4mEdo** [comment]
No problem for me on opera 38, Mac Os 10.11
```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

**Comment by jabbink** [comment]
>Issue still happening

Can you press F12 and check if the console gives any errors?

**Comment by jabbink** [comment]
Also

>Are you guys trying http://127.0.0.1:8000 or http://localhost:8000

**Comment by Pepejson** [comment]
No error in console. Just chrome error screen saying ERR_EMPTY_RESPONSE

**Comment by nullsumme** [comment]
Can't build on Windows:

* What went wrong:
Execution failed for task ':PokeGOAPI-Java:generateProto'.
> java.io.IOException: Cannot run program "C:\Users\********\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protoc\3.0.0-beta-3\71e76cad4f9b30aab172c44035d343c5bab47815\protoc-3.0.0-beta-3-windows-x86_64.exe": CreateProcess error=206, Der Dateiname oder die Erweiterung ist zu lang

(pathname is to long)

**Comment by JPhix** [comment]
from debian where i have a working webserver the socket server isnt working 
http://i.xajoo-services.eu/vtwx5j.png
and then from windows the web server doesnt even load but the socket server loads up fine 
http://i.xajoo-services.eu/8jlglv.png
as you can see im tying all 3 ips on my local machine

**Comment by celsian** [comment]
As @JPhix said, on my Debian server the webserver is working, the socket is refusing connections.

**Comment by ArtursGailis1995** [comment]
As already mentioned in #233 the WEB GUI is not working for me on any Windows 10 machine. Tried even clean install on virtual machine and it still can build successfully, run successfully but it shows ERR_EMPTY_RESPONSE in Chrome and Connection reset in Firefox.

On WIndows 8.1 it works flawlessy.

On Windows 10 -  WEB GUI never ever worked with any build.

**Comment by jabbink** [comment]
Can you replace the `slf4j-nop` dependency in `build.gradle` with something like `slf4j-simple`?

Maybe the ports are already in use on your system? Try a different port maybe>

**Comment by Pepejson** [comment]
Done that with slf4j-simple (./gradlew clean build fatJar) - still the same but got some new info in console.

port 8001
![image](https://cloud.githubusercontent.com/assets/3199312/17189300/35885b14-5441-11e6-8eac-cf299c2cc01c.png)
port 8000
![image](https://cloud.githubusercontent.com/assets/3199312/17189313/41ae7ef0-5441-11e6-9155-d9b89580617d.png)

**Comment by ArtursGailis1995** [comment]
@jabbink Also tried different ports and even editing hosts file to make it point to a custom name - set ports to 2015 and 2016; and domain to pokemon.bot in hosts file.

It still gives "ERR_EMPTY RESPONSE" so it may be Windows bug or "feature".

**Comment by JPhix** [comment]
Running webserver on port 8000
[main] INFO com.corundumstudio.socketio.SocketIOServer - Session store / pubsub factory used: MemoryStoreFactory (local session store only)
[nioEventLoopGroup-2-1] INFO com.corundumstudio.socketio.SocketIOServer - SocketIO server started at port: 8001
ok so it seems that the gui interface can listen on an external ip address but the socketIO listens on localhost 
tested by installing text browser on my server and going to the address

**Comment by jabbink** [comment]
https://www.reddit.com/r/java/comments/25pbbd/writing_java_socket_http_server_chrome_thinks_the/

Unfortunately that gist is offline. And I don't see any line closing the input before the output is written.

**Comment by jabbink** [comment]
Maybe try to replace the `t.responseBody.close()` with

```kotlin
            t.responseBody.flush()
            t.responseBody.close()
            t.requestBody.close()
```

**Comment by marcx093** [comment]
I don't know if this can help, but i managed to get it working, i'm using windows 10 with chrome browser, so i doubt it should be a windows 10 bug

**Comment by jabbink** [comment]
And last weird thing that could be different across computers: ipv4 vs ipv6 (because it works for me on Chrome with Windows 10)

Try http://[::1]:8000/

**Comment by marcx093** [comment]
Btw do you know how to cancel the queued location to go? Like i put too many (yellow fingers down)

**Comment by Pepejson** [comment]
> Maybe try to replace the t.responseBody.close() with
> ```
>             t.responseBody.flush()
>             t.responseBody.close()
>             t.requestBody.close()
> ```

Could you tell me in which file?

**Comment by siimveskilt** [comment]
Doesn't work with chrome or firefox or edge for me.

**Comment by JPhix** [comment]
managed to get it working on debian by changing socketio to run on any ip rather than just localhost since im not running it localy works fine now

**Comment by langerhans** [comment]
@JPhix I put in #521 for that just now :+1:

**Comment by jabbink** [comment]
#521 merged, does this fix your problem?

**Comment by Pepejson** [comment]
Still the same, even done the trick with `t.responseBody.flush()` I really don't know what's wrong with it. Even tried running bot on MacOS and Safari & Firefox giving the same result.

**Comment by Pepejson** [comment]
I don't know what caused this issue but compiled latest develop and everything is working. For me it can be closed.
