### ISSUE TITLE
Error running loop BotLoop & ProfileLoop! 

### ISSUE THREAD

**Issue by flybirdkk** [jabbink/PokemonGoBot#730]
**Error running loop BotLoop!** 
com.pokegoapi.exceptions.RemoteServerException: Contents of buffer are null
	at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:119)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:154)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
	at com.pokegoapi.api.map.pokemon.CatchablePokemon$3.handle(CatchablePokemon.java:419)
	at com.pokegoapi.api.map.pokemon.CatchablePokemon$3.handle(CatchablePokemon.java:400)
	at com.pokegoapi.util.FutureWrapper.getResult(FutureWrapper.java:78)
	at com.pokegoapi.util.FutureWrapper.get(FutureWrapper.java:53)
	at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:108)
	at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:94)
	at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:346)
	at ink.abb.pogo.scraper.util.pokemon.CatchablePokemonKt.catch(CatchablePokemon.kt:27)
	at ink.abb.pogo.scraper.util.pokemon.CatchablePokemonKt.catch(CatchablePokemon.kt:115)
	at ink.abb.pogo.scraper.util.pokemon.CatchablePokemonKt.catch(CatchablePokemon.kt:42)
	at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:62)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:201)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:123)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:34)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:163)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:34)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:292)
	at java.lang.Thread.run(Thread.java:745)

**Error running loop ProfileLoop!** 
com.pokegoapi.exceptions.RemoteServerException: Contents of buffer are null
	at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:119)
	at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:94)
	at com.pokegoapi.api.map.fort.Pokestop.getDetails(Pokestop.java:229)
	at ink.abb.pogo.scraper.gui.SocketServer.sendPokestop(SocketServer.kt:105)
	at ink.abb.pogo.scraper.tasks.LootOneNearbyPokestop.run(LootOneNearbyPokestop.kt:52)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:201)
	at ink.abb.pogo.scraper.tasks.ProcessPokestops.run(ProcessPokestops.kt:52)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:201)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:130)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:34)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:163)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:34)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:292)
	at java.lang.Thread.run(Thread.java:745)
com.pokegoapi.exceptions.RemoteServerException: Contents of buffer are null
	at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:119)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:154)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
	at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:74)
	at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:22)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:201)
	at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:115)
	at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:34)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:163)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:34)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:292)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Cypherke** [comment]
what version are you using?

**Comment by flybirdkk** [comment]
v0.5.0 alpha 4

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by flybirdkk** [comment]
# Desired probability to catch Pokemon with 1 throw
desired_catch_probability=0.4

# Desired probability to catch unwanted Pokemon (obligatory_transfer; low IV; low CP)
# Set to -1 to not attempt catching at all
desired_catch_probability_unwanted=1

# Number of nearest unused pokestops to randomly select
# The next pokestop from (1/infinite)
random_next_pokestop_selection=5

## Walking
# Meters per second
speed=2.8

# Should the bot follow the streets (true) or just go directly to pokestops/waypoints
follow_streets=false

# Should the bot loot the pokestops (true/false)
loot_pokestop=true

# Should the bot catch pokemons (true/false)
catch_pokemon=true

# Should the bot auto fill incubators with eggs (true/false)
auto_fill_incubator=true

## Items drop
# Should the bot EVER drop items (true/false)
drop_items=true

# Max number of each item that the bot should keep if "drop_items" is enabled
# Use -1 in an item to never drop this specific item
# The default values add up to 350
item_revive=20
item_max_revive=10
item_potion=0
item_super_potion=30
item_hyper_potion=50
item_max_potion=50
item_poke_ball=40
item_great_ball=50
item_ultra_ball=50
item_master_ball=10
item_razz_berry=40
item_lucky_egg=-1
item_incense=-1
item_lure_module=-1

## Extra Info
# Should the bot display rewards pokestop (true/false)
display_pokestop_rewards=true

# Should the bot display rewards when catching pokemon (true/false)
display_pokemon_catch_rewards=true

# Display keepalive coordinates
display_keepalive=true

# Should the bot display information of where it's walking to (true/false)
# This will show the name of the pokestop that it's walking to and
#   replace on the loot log the pokestop id for its name
# WARNING:  this will increase the https requests without any need. If
#           the servers are slow it's recommended to turn off this setting
display_pokestop_name=true

## Pokemon Transfer
# Should the bot auto transfer duplicate pokemon
autotransfer=true

# Minimum amount of pokemon type to keep
keep_pokemon_amount=1

# Maximum amount of pokemon type to keep (-1 to keep all)
max_pokemon_amount=2

# Sort by IV first instead of CP
sort_by_iv=false

# Always throw curveballs
always_curve=false

# Never use berries
never_use_berries=true

# Allow leaving the starting area
allow_leave_start_area=true unlimited

# Max distance from starting point the bot should ever go in meters
# (-1: only limited by the initial pokestops (~3*3km); with allow_leave_start_area=true unlimited)
spawn_radius=-1

# Set timer in seconds to go back to the starting pokestop (-1 disabled)
timerWalkToStartPokeStop=-1

# Set profile update timer (Default: 60)
profile_update_timer=60

# Minimum IV percentage to keep a pokemon (to ignore IV: use -1)
# between 0 and 100, suggested 80
transfer_iv_threshold=80

# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=400

# List of pokemon you don't want to transfer regardless of CP
# The names must be divided by a ","
# If you want all pokemons to be transferred just leave it blank
ignored_pokemon=

# List of pokemon you always want to transfer regardless of CP
obligatory_transfer=

# Port where the webserver (gui) should listen, 0 = do not listen
gui_port=8000
# Port where the socketserver should listen, 0 = do not listen
gui_port_socket=8001

**Comment by kasagon** [comment]
I have the same problem

Commit 6d361a6  

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by yashendra2797** [comment]
I've been having this problem since alpha2, which was the first version I used. Normally the bot will recover, but after exactly 90 minutes, the bot just gets stuck on this issue, forcing a restart. I didn't comment before because there have been several posts about this, and I didn't wanna clutter the devs feeds.

**Comment by timchen100** [comment]
Same here. For me the Bot starts and stays in one location and loots the same pokestop over and over.

**Comment by masiarb** [comment]
I'm using 0.4.3 and having the same issue. On my side, the bot often spams this error but it somehow recovers and still runs, moves, catches pokemon, gets pokestops rewards, and often (but not always I noticed) puts eggs into the incubators. Still, it would be better if there was no error :).

My error specifically addresses the RPC updateInventories (`at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:114)`) and removeItem (`at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:82)`). Here the full stack trace of the errors:

```
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:82)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:163)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:111)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:30)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:128)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:30)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:80)
	... 7 more
```

```
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:82)
	at ink.abb.pogo.scraper.tasks.DropUselessItems.run(DropUselessItems.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:163)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:111)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:30)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:128)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:30)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
	at com.pokegoapi.api.inventory.ItemBag.removeItem(ItemBag.java:80)
	... 7 more
```

**Comment by alexvkcr** [comment]
Same here with version 0.4.3

**Comment by jabbink** [comment]
As far as I know this is fixed (the exact 90 minutes timeout); was a bug in the API.

**Comment by husbeard** [comment]
Yep, I have the same exact problem. But this only happens on my google accounts. The PTC accounts seem to run better. Output;
03 Aug 06:50:11: Error running loop BotLoop!
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
        at java.lang.Thread.run(Unknown Source)
03 Aug 06:50:12: Stopping SocketServer...
03 Aug 06:50:12: Stopping bot loops...
03 Aug 06:50:12: All bot loops stopped.
03 Aug 06:50:16: Stopped SocketServer.

Not sure about the time frame, but this one happened less than 60 minutes in.

**Comment by konstantinj** [comment]
Hi, can confirm that it still happens with the stable 0.5.0 but only with google accounts. I'll write a watchdog for this.

**Comment by masiarb** [comment]
I second this.

```
D/RequestHandler: Authenticated with static token
08 Aug 11:39:50 (default: BotLoop): Error running loop BotLoop! 
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.api.map.fort.Pokestop.loot(Pokestop.java:154)
	at ink.abb.pogo.scraper.tasks.LootOneNearbyPokestop.run(LootOneNearbyPokestop.kt:39)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:221)
	at ink.abb.pogo.scraper.tasks.ProcessPokestops.run(ProcessPokestops.kt:50)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:221)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:131)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:33)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:169)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 10 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:217)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
	at java.lang.Thread.run(Thread.java:745)
```
