### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by vdianl** [jabbink/PokemonGoBot#79]
Build ends with an Exception.

_./gradlew build_
```
:compileKotlin
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt: (35, 38): Cannot access 'username': it is 'private' in 'PlayerProfile'
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt: (36, 38): Cannot access 'team': it is 'private' in 'PlayerProfile'
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt: (37, 42): Cannot access 'currencies': it is 'private' in 'PlayerProfile'
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt: (38, 42): Cannot access 'currencies': it is 'private' in 'PlayerProfile'
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt: (42, 13): Unresolved reference: pokebank
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt: (42, 45): Unresolved reference: it
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt: (42, 67): Unresolved reference: it
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt: (42, 88): Unresolved reference: it
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt: (42, 101): Cannot choose among the following candidates without completing type inference: 
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit): Unit defined in kotlin.collections
@HidesMembers public inline fun <K, V> Map<???, ???>.forEach(action: (Map.Entry<???, ???>) -> Unit): Unit defined in kotlin.collections
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt: (42, 119): Unresolved reference: it
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/Settings.kt: (41, 107): Unresolved reference: Base64
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/tasks/CatchOneNearbyPokemon.kt: (27, 36): Unresolved reference: bag
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/tasks/CatchOneNearbyPokemon.kt: (34, 40): Unresolved reference: bag
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/tasks/DropUselessItems.kt: (24, 32): Unresolved reference: bag
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/tasks/DropUselessItems.kt: (27, 38): Unresolved reference: bag
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/tasks/ReleasePokemon.kt: (21, 38): Unresolved reference: pokebank
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/tasks/ReleasePokemon.kt: (21, 66): Unresolved reference: it
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/tasks/ReleasePokemon.kt: (26, 24): Cannot choose among the following candidates without completing type inference: 
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit): Unit defined in kotlin.collections
@HidesMembers public inline fun <K, V> Map<???, ???>.forEach(action: (Map.Entry<???, ???>) -> Unit): Unit defined in kotlin.collections
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/tasks/ReleasePokemon.kt: (27, 26): Unresolved reference: it
e: /home/user/pogobot/PokemonGoBot/src/main/kotlin/ink/abb/pogo/scraper/tasks/ReleasePokemon.kt: (27, 56): Unresolved reference: it
:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.06 secs

```

**-- STACKTRACE**

Exception is:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileKotlin'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:241)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:214)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:207)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.GradleException: Compilation error. See log for more details
	at org.jetbrains.kotlin.gradle.tasks.KotlinCompile$callCompiler$10.invoke(Tasks.kt:355)
	at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler(Tasks.kt:364)
	at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompiler(Tasks.kt:148)
	at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.execute(Tasks.kt:110)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 60 more


```

**Comment by zeryl** [comment]
+1

**Comment by davidmann4** [comment]
api changed alot of classnames... use the jar file until it is fixed 

https://github.com/jabbink/PokemonGoBot/releases

**Comment by jabbink** [comment]
Fixed.

**Comment by davidmann4** [comment]
still not building for me - had to change imports like

import POGOProtos.Inventory.Items.ItemIdOuterClass.ItemId

to 

import POGOProtos.Inventory.ItemIdOuterClass.ItemId

**Comment by pr0ves** [comment]
You need to update the dependencies with `gradle build --refresh-dependencies`
But when updating it says tha ti t can't find com.github.Grover-c13:PokeGOAPI-Java:master-SNAPSHOT

**Comment by davidmann4** [comment]
i just deleted my gradle folder - so i guess i had the newest files - will try your aproach

**Comment by pr0ves** [comment]
@davidmann4 See #92

**Comment by jabbink** [comment]
Jitpack build is broken: https://jitpack.io/#Grover-c13/PokeGOAPI-Java/f5b53683d2
