### ISSUE TITLE
Bot wont start

### ISSUE THREAD

**Issue by qwertychacha2002** [jabbink/PokemonGoBot#921]
**Description:**
I get this issue when I attempt to start the bot:
`                                  ,'\
    _.----.        ____         ,'  _\   ___    ___     ____        ;-.               ,
_,-'       `.     |    |  /`.   \,-'    |   \  /   |   |    \  |`.   \ '.           .'/
\      __    \    '-.  | /   `.  ___    |    \/    |   '-.   \ |  |   \  \ .---. .-' /
 \.    \ \   |  __  |  |/    ,','_  `.  |          | __  |    \|  |    '. '     `\_.'
   \    \/   /,' _`.|      ,' / / / /   |          ,' _`.|     |  |      |(),()  |     ,
    \     ,-'/  /   \    ,'   | \/ / ,`.|         /  /   \  |     |      (  __   /   .' \
     \    \ |   \_/  |   `-.  \    `'  /|  |    ||   \_/  | |\    |     .''.___.'--,/\_,|
      \    \ \      /       `-.`.___,-' |  |\  /| \      /  | |   |    {  /     \   }   |
       \    \ `.__,'|  |`-._    `|      |__| \/ |  `.__,'|  | |   |     '.\     /_.'    /
        \_.-'       |__|    `-._ |              '-.|     '-.| |   |      |'-.-',  `; _.'
                                `'                            '-._|      |  |  |   |`
                                                                         `""`""`"""`

09 Aug 16:23:08 [main] - Running with Spring Boot v1.3.6.RELEASE, Spring v4.2.7.RELEASE
09 Aug 16:23:08 [main] - No active profile set, falling back to default profiles: default
09 Aug 16:23:10 [main] - UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
09 Aug 16:23:10 [main] - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
09 Aug 16:23:11 [main] - Application startup failed
java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:186)
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:142)
	... 19 common frames omitted

`
**Version:**
PokemonGoBot-0.5.1.jar

**Operating System:**
OSX El Capitan Version 10.11.5 (15F34)

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by vamirineni87** [comment]
Please look at teh error in detail. Caused by: java.net.BindException: Address already in use
This has been addressed multiple times. Make sure you are using different port number if you are setting up multiple bots. Sometimes I have noticed as well, even after setting the different port number this issue pops up. I just disabled the web interface.

**Comment by qwertychacha2002** [comment]
How do I change the port number? I changed the 8001 to 8002 in the config file and it still crashes on startup

**Comment by Cypherke** [comment]
make sure you kill all java processes, there might be some lingering

**Comment by qwertychacha2002** [comment]
How do I kill them? Terminal is closed on my mac.

**Comment by Danman00** [comment]
In your Programs you should have a folder called Systemprograms with a Screwdriver symbol in this folder there is an application called activity monitor 
![bildschirmfoto 2016-08-09 um 22 50 40](https://cloud.githubusercontent.com/assets/20669449/17533124/bc7ab3c8-5e83-11e6-9383-a1c91e63fddc.png)

kill the java process with the stop sign symbol on teh top left corner

**Comment by qwertychacha2002** [comment]
Thank you! I had did have a second java process running in the backround.
